### PR TITLE
Robby/news

### PR DESCRIPTION
**Pull request by robbysingh23**
This pull request isn't all that impressive. I just wrote the api key and base url. The api key won't allow us to filter by states. Only news from countries. We shall discuss what to do with this. Or you guys can check if i missed anything from the documentation,

### CODE REVIEW

**Comment by robbysingh23** [comment]
Here's a basic modal made with bootstrap. All we need to do is implement this within our index html file.

**Comment by robbysingh23** [comment]
So i created a new fetch api via axios. I basically used what Luqmaan did as a guide. It's synced up with the search bar. It'll actually capture the user inputs. But... i'm getting a network error and a "CORS" error. So, some troubleshooting would be required tomorrow from anyone that's free. It does look minor.

**Review by Logrythmic — COMMENTED** [review]
Just leaving some comments while I look over things. The modal is a shell essentially that we will fill in once we get the news API working, I am pulling and testing the files to make sure everything is working. will post a follow up in a few minutes

**Review by Logrythmic — APPROVED** [review]
ok I'm going to merge this and send back a Pull request for the changes I will make. I figured out how to stop the error you mentioned. Its a syntax error on the URL.

**Pull request merged**
